import { Company, Employee, AttendanceRecord, LeaveRequest, UserProfile } from '../types';

export const currentUserSuperAdmin: UserProfile = {
  id: 'usr_super_01',
  name: 'Anand Patel',
  email: 'superadmin@hazree.com',
  role: 'SUPER_ADMIN',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  companyName: 'Hazree Platform HQ',
};

export const currentUserCompanyAdmin: UserProfile = {
  id: 'usr_cmp_01',
  name: 'Rajesh Sharma',
  email: 'admin@tatatech.com',
  role: 'COMPANY_ADMIN',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  companyName: 'Tata Tech Solutions',
};

export const initialCompanies: Company[] = [];


export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att_01',
    employeeId: 'emp_01',
    employeeName: 'Aarav Sharma',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Engineering',
    date: '2026-08-12',
    checkInTime: '09:02 AM',
    checkOutTime: '06:15 PM',
    status: 'Present',
    workHours: '9h 13m',
    location: 'Mumbai BKC Office (Geofence Verified)',
    device: 'iOS Hazree App (Facial recognition)',
  },
  {
    id: 'att_02',
    employeeId: 'emp_02',
    employeeName: 'Ananya Deshmukh',
    employeeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Human Resources',
    date: '2026-08-12',
    checkInTime: '08:55 AM',
    checkOutTime: '05:45 PM',
    status: 'Present',
    workHours: '8h 50m',
    location: 'Mumbai BKC Office',
    device: 'Android Kiosk Punch',
  },
  {
    id: 'att_03',
    employeeId: 'emp_03',
    employeeName: 'Rohan Joshi',
    employeeAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Sales & Marketing',
    date: '2026-08-12',
    checkInTime: '09:48 AM',
    checkOutTime: '--',
    status: 'Late',
    workHours: 'Active',
    location: 'Field Client Visit (Andheri)',
    device: 'Mobile GPS Tag',
  },
  {
    id: 'att_04',
    employeeId: 'emp_04',
    employeeName: 'Sneha Patel',
    employeeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Design & UI',
    date: '2026-08-12',
    checkInTime: '--',
    checkOutTime: '--',
    status: 'Absent',
    workHours: '0h',
    location: 'Not Clocked In',
    device: 'N/A',
  },
  {
    id: 'att_05',
    employeeId: 'emp_05',
    employeeName: 'Karan Singhania',
    employeeAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Finance & Accounts',
    date: '2026-08-12',
    checkInTime: '09:05 AM',
    checkOutTime: '01:30 PM',
    status: 'Half Day',
    workHours: '4h 25m',
    location: 'Mumbai BKC Office',
    device: 'Web Browser Punch',
  },
  {
    id: 'att_06',
    employeeId: 'emp_06',
    employeeName: 'Deepika Nair',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    companyId: 'cmp_101',
    department: 'Operations',
    date: '2026-08-12',
    checkInTime: '09:12 AM',
    checkOutTime: '--',
    status: 'Present',
    workHours: 'Active',
    location: 'Thane Warehouse Hub',
    device: 'Fingerprint Biometric',
  },
];

export const mockEmployees: Employee[] = [];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'lv_01',
    employeeId: 'emp_04',
    employeeName: 'Sneha Patel',
    employeeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    department: 'Design & UI',
    leaveType: 'Casual',
    startDate: '2026-08-12',
    endDate: '2026-08-14',
    daysCount: 3,
    reason: 'Family event and personal travel to Vadodara.',
    status: 'Pending',
    appliedOn: '2026-08-10',
  },
  {
    id: 'lv_02',
    employeeId: 'emp_06',
    employeeName: 'Deepika Nair',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    department: 'Operations',
    leaveType: 'Sick',
    startDate: '2026-08-15',
    endDate: '2026-08-16',
    daysCount: 2,
    reason: 'High fever and dental checkup appointment.',
    status: 'Approved',
    appliedOn: '2026-08-11',
  },
  {
    id: 'lv_03',
    employeeId: 'emp_03',
    employeeName: 'Rohan Joshi',
    employeeAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    department: 'Sales & Marketing',
    leaveType: 'Paid',
    startDate: '2026-08-20',
    endDate: '2026-08-22',
    daysCount: 3,
    reason: 'Annual family vacation leave.',
    status: 'Pending',
    appliedOn: '2026-08-12',
  },
];
