import {
  EmployeeProfile,
  PunchRecord,
  LeaveBalance,
  LeaveRequest,
  ShiftDay,
  PricingPlan,
} from "../types/customer";

export const INITIAL_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 101,
    fullName: "Aarav Sharma",
    email: "aarav.sharma@techcorp.in",
    phone: "+91 98765 43210",
    designation: "Senior Frontend Engineer",
    department: "Engineering",
    employeeCode: "EMP-1001",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    shiftName: "General Shift",
    shiftStart: "09:30",
    shiftEnd: "18:30",
    companyName: "Apex Innovations Pvt Ltd",
    companyId: 1,
    pin: "1234",
    geofenceRequired: true,
    photoVerificationRequired: true,
    baseSalary: 85000,
  },
  {
    id: 102,
    fullName: "Priya Patel",
    email: "priya.patel@techcorp.in",
    phone: "+91 98765 43211",
    designation: "Product Designer (UI/UX)",
    department: "Design & Product",
    employeeCode: "EMP-1002",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    shiftName: "Flexible Morning Shift",
    shiftStart: "10:00",
    shiftEnd: "19:00",
    companyName: "Apex Innovations Pvt Ltd",
    companyId: 1,
    pin: "4321",
    geofenceRequired: true,
    photoVerificationRequired: false,
    baseSalary: 78000,
  },
  {
    id: 103,
    fullName: "Rohan Verma",
    email: "rohan.verma@techcorp.in",
    phone: "+91 98765 43212",
    designation: "Operations & Sales Lead",
    department: "Operations",
    employeeCode: "EMP-1003",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    shiftName: "Field & Operations Shift",
    shiftStart: "09:00",
    shiftEnd: "18:00",
    companyName: "Apex Innovations Pvt Ltd",
    companyId: 1,
    pin: "7890",
    geofenceRequired: false,
    photoVerificationRequired: true,
    baseSalary: 65000,
  },
];

export const INITIAL_LEAVE_BALANCE: LeaveBalance = {
  casual: { total: 12, used: 4, remaining: 8 },
  sick: { total: 10, used: 2, remaining: 8 },
  earned: { total: 15, used: 3, remaining: 12 },
  unpaid: { used: 0 },
};

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 1,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    leaveType: "Casual",
    startDate: "2026-08-21",
    endDate: "2026-08-22",
    daysCount: 2,
    isHalfDay: false,
    reason: "Family function in hometown",
    status: "Pending",
    appliedOn: "2026-08-15",
  },
  {
    id: 2,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    leaveType: "Sick",
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    daysCount: 1,
    isHalfDay: false,
    reason: "Severe fever and flu recovery",
    status: "Approved",
    appliedOn: "2026-08-04",
    reviewedBy: "Aditi Rao (HR Manager)",
    reviewComment: "Approved. Take rest and submit prescription copy if required.",
  },
  {
    id: 3,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    leaveType: "Earned",
    startDate: "2026-07-10",
    endDate: "2026-07-14",
    daysCount: 5,
    isHalfDay: false,
    reason: "Summer vacation trip",
    status: "Approved",
    appliedOn: "2026-07-01",
    reviewedBy: "Vikram Malhotra (Director)",
    reviewComment: "Approved. Have a great vacation!",
  },
];

export const INITIAL_PUNCH_RECORDS: PunchRecord[] = [
  {
    id: 501,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-17",
    punchInTime: "09:28:15",
    punchOutTime: null,
    status: "Present",
    workHours: 4.8,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 14,
    punchType: "Web App",
    notes: "Biometric & Geofence GPS Verified",
  },
  {
    id: 502,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-16",
    punchInTime: "09:42:00",
    punchOutTime: "18:45:10",
    status: "Late",
    workHours: 9.05,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 22,
    punchType: "Mobile GPS",
    notes: "Late by 12 mins due to rain traffic",
  },
  {
    id: 503,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-15",
    punchInTime: "00:00:00",
    punchOutTime: null,
    status: "Holiday",
    workHours: 0,
    punchLocation: "National Holiday",
    geofenceStatus: "Inside",
    punchType: "Web App",
    notes: "Independence Day Holiday",
  },
  {
    id: 504,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-14",
    punchInTime: "09:25:00",
    punchOutTime: "18:32:00",
    status: "Present",
    workHours: 9.11,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 8,
    punchType: "Kiosk PIN",
  },
  {
    id: 505,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-13",
    punchInTime: "09:30:10",
    punchOutTime: "14:00:00",
    status: "Half Day",
    workHours: 4.5,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 10,
    punchType: "Web App",
    notes: "Half day approved for personal work",
  },
  {
    id: 506,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-12",
    punchInTime: "09:20:00",
    punchOutTime: "18:35:00",
    status: "Present",
    workHours: 9.25,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 15,
    punchType: "Web App",
  },
  {
    id: 507,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-11",
    punchInTime: "09:15:00",
    punchOutTime: "18:40:00",
    status: "Present",
    workHours: 9.41,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 12,
    punchType: "Web App",
  },
  {
    id: 508,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-10",
    punchInTime: "09:24:00",
    punchOutTime: "18:30:00",
    status: "Present",
    workHours: 9.1,
    punchLocation: "Apex HQ, Sector 62, Noida",
    geofenceStatus: "Inside",
    distanceMeters: 16,
    punchType: "Web App",
  },
  {
    id: 509,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-09",
    punchInTime: "00:00:00",
    punchOutTime: null,
    status: "Day Off",
    workHours: 0,
    punchLocation: "Sunday Weekly Off",
    geofenceStatus: "Inside",
    punchType: "Web App",
  },
  {
    id: 510,
    employeeId: 101,
    employeeName: "Aarav Sharma",
    employeeCode: "EMP-1001",
    date: "2026-08-08",
    punchInTime: "00:00:00",
    punchOutTime: null,
    status: "Day Off",
    workHours: 0,
    punchLocation: "Saturday 2nd Off",
    geofenceStatus: "Inside",
    punchType: "Web App",
  },
];

export const INITIAL_SHIFTS: ShiftDay[] = [
  {
    dayName: "Monday",
    date: "17 Aug 2026",
    isOff: false,
    shiftTitle: "Regular General Shift",
    startTime: "09:30 AM",
    endTime: "06:30 PM",
    graceTimeMinutes: 15,
    lunchBreakMinutes: 45,
    location: "Main HQ - Floor 3",
  },
  {
    dayName: "Tuesday",
    date: "18 Aug 2026",
    isOff: false,
    shiftTitle: "Regular General Shift",
    startTime: "09:30 AM",
    endTime: "06:30 PM",
    graceTimeMinutes: 15,
    lunchBreakMinutes: 45,
    location: "Main HQ - Floor 3",
  },
  {
    dayName: "Wednesday",
    date: "19 Aug 2026",
    isOff: false,
    shiftTitle: "Regular General Shift",
    startTime: "09:30 AM",
    endTime: "06:30 PM",
    graceTimeMinutes: 15,
    lunchBreakMinutes: 45,
    location: "Main HQ - Floor 3",
  },
  {
    dayName: "Thursday",
    date: "20 Aug 2026",
    isOff: false,
    shiftTitle: "Regular General Shift",
    startTime: "09:30 AM",
    endTime: "06:30 PM",
    graceTimeMinutes: 15,
    lunchBreakMinutes: 45,
    location: "Main HQ - Floor 3",
  },
  {
    dayName: "Friday",
    date: "21 Aug 2026",
    isOff: false,
    shiftTitle: "Regular General Shift (Happy Hours)",
    startTime: "09:30 AM",
    endTime: "06:00 PM",
    graceTimeMinutes: 15,
    lunchBreakMinutes: 45,
    location: "Main HQ - Floor 3",
  },
  {
    dayName: "Saturday",
    date: "22 Aug 2026",
    isOff: true,
    shiftTitle: "Weekly Off",
    startTime: "-",
    endTime: "-",
    graceTimeMinutes: 0,
    lunchBreakMinutes: 0,
    location: "Home",
  },
  {
    dayName: "Sunday",
    date: "23 Aug 2026",
    isOff: true,
    shiftTitle: "Sunday Weekend",
    startTime: "-",
    endTime: "-",
    graceTimeMinutes: 0,
    lunchBreakMinutes: 0,
    location: "Home",
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter Free",
    tagline: "Essential attendance tracking for small teams & startups",
    pricePerEmpMonthly: 0,
    billingPeriod: "monthly",
    features: [
      "Up to 10 Employees Free Forever",
      "Web & Mobile GPS Punch In/Out",
      "Office Geofencing (1 Location)",
      "Daily Attendance Summaries",
      "Leave Application & Approvals",
      "Basic CSV/Excel Export",
      "Community Support",
    ],
    recommendedFor: "Startups & Micro Businesses",
    ctaText: "Get Started Free",
  },
  {
    id: "growth",
    name: "Growth Pro",
    tagline: "The #1 automated workforce & shift management suite",
    pricePerEmpMonthly: 49,
    billingPeriod: "monthly",
    popular: true,
    features: [
      "Unlimited Employees & Multi-Branch",
      "AI Selfie & Anti-Spoof Liveness Check",
      "Tablet Front-Desk Kiosk Mode with PIN",
      "Shift Rostering & Night Shift Rules",
      "Overtime & Late-Coming Penalty Rules",
      "Automated WhatsApp & Email Reports",
      "1-Click Payroll Salary Computations",
      "24/7 Priority Support & Dedicated Account Mgr",
    ],
    recommendedFor: "Growing SMEs, Retail & IT Firms",
    ctaText: "Start 14-Day Free Trial",
  },
  {
    id: "enterprise",
    name: "Enterprise Custom",
    tagline: "Tailored biometric sync, custom APIs & dedicated SLAs",
    pricePerEmpMonthly: 99,
    billingPeriod: "monthly",
    features: [
      "Everything in Growth Pro",
      "Hardware Biometric Device Sync (ZKTeco, Realtime)",
      "Custom ERP/HRMS API Webhooks (SAP, Zoho, Darwinbox)",
      "Custom Geofence Polygons & Beacons",
      "Dedicated On-Premise / Private Cloud Option",
      "Custom SLA with 99.99% Uptime Guarantee",
      "Custom Training & Employee Onboarding",
    ],
    recommendedFor: "Large Enterprises, Plants & Chain Stores",
    ctaText: "Contact Enterprise Sales",
  },
];

export const TESTIMONIALS = [
  {
    name: "Vikramaditya Singhal",
    role: "COO, Apex Retailers (42 Outlets)",
    text: "Hazree eliminated buddy punching and saved our retail chain over 180 hours of manual attendance verification every month. The Geofenced kiosk mode is pure gold!",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80",
    rating: 5,
    stats: "Saved ₹1.8L/month on leakage",
  },
  {
    name: "Ananya Deshmukh",
    role: "Head of HR, Synapse Digital Labs",
    text: "Our engineers love the simple web & mobile selfie punch. Leave requests are approved in seconds and monthly payroll export happens with just one click.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    rating: 5,
    stats: "100% On-time Salary Disbursal",
  },
  {
    name: "Rajeshwar Guha",
    role: "Plant Director, Everest Packagings",
    text: "Managing 3 rotational shifts across 280 factory workers was a nightmare before Hazree. Now the shift roster and automated overtime tracking work seamlessly.",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    rating: 5,
    stats: "Zero Shift Discrepancies",
  },
];

export const FAQS = [
  {
    question: "How does GPS Geofencing work on mobile and web?",
    answer:
      "Hazree captures device GPS coordinates upon punching and verifies if the employee is physically located within the employer-defined radius (e.g. 50 meters of the office or client site). Punches outside the zone are either flagged or rejected according to company policies.",
  },
  {
    question: "Can we use a single tablet or phone as an office check-in Kiosk?",
    answer:
      "Yes! With Hazree Kiosk Mode, you can mount any standard Android tablet or iPad at your reception/entry. Employees simply enter their 4-digit PIN or scan their QR badge with instant camera verification.",
  },
  {
    question: "Is Hazree compliant with statutory payroll calculations in India?",
    answer:
      "Absolutely. Hazree automatically calculates present days, half days, paid leaves, sandwich holiday rules, and overtime hours, generating ready-to-use payroll spreadsheets compliant with PF/ESIC norms.",
  },
  {
    question: "Can I try Hazree for free before purchasing?",
    answer:
      "Yes! Our Starter plan is 100% free forever for up to 10 employees. For larger teams, you get a full-featured 14-day free trial of the Growth Pro plan with no credit card required.",
  },
];
